Repository codestates-seb/seb43_main_013, pull requests merged in 2023-05, with the labels that each got.

#6 Be feat/member
  server/build.gradle
  server/src/main/java/com/CreatorConnect/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/CreatorConnect/server/audit/Auditable.java
  server/src/main/java/com/CreatorConnect/server/exception/BusinessLogicException.java
  server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
  server/src/main/java/com/CreatorConnect/server/response/ErrorResponse.java
  server/src/main/java/com/CreatorConnect/server/utils/CustomBeanUtils.java
  server/src/main/java/com/CreatorConnect/server/utils/UriCreator.java
  server/src/main/java/com/CreatorConnect/server/validator/NotSpace.java
  server/src/main/java/com/CreatorConnect/server/validator/NotSpaceValidator.java
Labels: 💾backend

#10 Be feat/member CRUD
  server/src/main/java/com/CreatorConnect/server/ServerApplication.java
  server/src/main/java/com/CreatorConnect/server/audit/Auditable.java
  server/src/main/java/com/CreatorConnect/server/audit/LocalDateTimeConverter.java
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/config/WebConfig.java
  server/src/main/java/com/CreatorConnect/server/auth/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/CreatorConnect/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/CreatorConnect/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberDto.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberLoginDto.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Follow.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Follower.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/mapper/MemberMapper.java
  server/src/main/java/com/CreatorConnect/server/member/repository/MemberRepository.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
  server/src/main/java/com/CreatorConnect/server/response/ErrorResponder.java
Labels: ✨ enhancement, 💾 backend

#20 Be feat/ spring security oauth2 - google
  server/build.gradle
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/config/WebConfig.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/google/GoogleOauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/CreatorConnect/server/exception/BusinessLogicException.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberDto.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/mapper/MemberMapper.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: ✨ enhancement, 💾 backend

#22 [be] fix: oauth google login 수정
  server/src/main/java/com/CreatorConnect/server/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/google/GoogleOauthController.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 🔧 fix, 💾 backend

#43 Be feat/member
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/attribute/OAuth2Attribute.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/config/OAuth2Configuration.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/KakaoController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/NaverController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/google/GoogleOauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/OAuth2MemberService.java
  server/src/main/java/com/CreatorConnect/server/auth/userdetails/MemberDetailsService.java
  server/src/main/java/com/CreatorConnect/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/CreatorConnect/server/category/controller/CategoryController.java
  server/src/main/java/com/CreatorConnect/server/category/dto/CategoryDto.java
  server/src/main/java/com/CreatorConnect/server/category/mapper/CategoryMapper.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
  server/src/main/java/com/CreatorConnect/server/response/ErrorResponder.java
  server/src/main/resources/data.sql
Labels: 🤪 bug, 💾 backend

#44 [be] feat: profileImageUrl 추가
  server/src/main/java/com/CreatorConnect/server/feedbackboard/dto/FeedbackBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/entity/FeedbackBoard.java
  server/src/main/java/com/CreatorConnect/server/freeboard/dto/FreeBoardDto.java
  server/src/main/java/com/CreatorConnect/server/freeboard/entity/FreeBoard.java
Labels: 🔧 fix, 💾 backend

#45 [be] fix: login response 수정
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
Labels: 💾 backend

#51 Be feat/security naver, kakao oauth login
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/attribute/OAuth2Attribute.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/config/OAuth2Configuration.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/KakaoController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/NaverController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/dto/KakaoProfile.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/dto/NaverProfile.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/dto/OAuthToken.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/KakaoApiService.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/NaverApiService.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/OAuth2MemberService.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
Labels: ✨ enhancement, 💾 backend

#54 [be] feat: response header 에 Access-Control-Expose-Headers 추가
  server/src/main/java/com/CreatorConnect/server/auth/filter/HttpServletWrappingFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtAuthenticationFilter.java
Labels: ✨ enhancement, 💾 backend

#56 [be] fix: member login response 수정
  server/build.gradle
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberDto.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
Labels: 🔧 fix, 💾 backend

#57 Be feat/member follow 로직 수정
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Follow.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Follower.java
  server/src/main/java/com/CreatorConnect/server/member/follow/entity/Follow.java
  server/src/main/java/com/CreatorConnect/server/member/follow/repository/FollowRepository.java
  server/src/main/java/com/CreatorConnect/server/member/follow/service/FollowService.java
Labels: 🔧 fix, 💾 backend

#59 Be feat/member follow following
  server/src/main/java/com/CreatorConnect/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/CreatorConnect/server/errorresponse/ErrorResponder.java
  server/src/main/java/com/CreatorConnect/server/errorresponse/ErrorResponse.java
  server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/follow/entity/Follow.java
  server/src/main/java/com/CreatorConnect/server/member/follow/repository/FollowRepository.java
  server/src/main/java/com/CreatorConnect/server/member/follow/service/FollowService.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: ✨ enhancement, 💾 backend

#60 [be] fix: feedbackboard
  server/src/main/java/com/CreatorConnect/server/feedbackboard/repository/FeedbackBoardRepository.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/service/FeedbackBoardService.java
Labels: 🔧 fix, 💾 backend

#61 [be] fix: 카테고리,피드백 카테고리 수정
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/category/controller/CategoryController.java
  server/src/main/java/com/CreatorConnect/server/category/dto/CategoryResponseDto.java
  server/src/main/java/com/CreatorConnect/server/category/service/CategoryService.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/feedbackcategory/controller/FeedbackCategoryController.java
  server/src/main/java/com/CreatorConnect/server/feedbackcategory/dto/FeedbackCategoryResponseDto.java
  server/src/main/java/com/CreatorConnect/server/feedbackcategory/service/FeedbackCategoryService.java
  server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
Labels: 🔧 fix, 💾 backend

#63 Be feat/member follow following
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberFollowResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/mapper/MemberMapper.java
Labels: ✨ enhancement, 💾 backend

#66 [be] feat: 자유 게시판 태그 기능 추가 및 게시글 목록 정렬 기준 추가
  server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/freeboard/dto/FreeBoardDto.java
  server/src/main/java/com/CreatorConnect/server/freeboard/entity/FreeBoard.java
  server/src/main/java/com/CreatorConnect/server/freeboard/mapper/FreeBoardMapper.java
  server/src/main/java/com/CreatorConnect/server/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/tag/dto/TagDto.java
  server/src/main/java/com/CreatorConnect/server/tag/entity/Tag.java
  server/src/main/java/com/CreatorConnect/server/tag/entity/TagToFreeBoard.java
  server/src/main/java/com/CreatorConnect/server/tag/mapper/TagMapper.java
  server/src/main/java/com/CreatorConnect/server/tag/repository/TagBoardRepository.java
  server/src/main/java/com/CreatorConnect/server/tag/repository/TagRepository.java
  server/src/main/java/com/CreatorConnect/server/tag/service/TagService.java
  server/src/main/resources/data.sql
Labels: ✨ enhancement, 🔧 fix, 💾 backend

#64 [fe] feat: 로그인 회원가입 요청 로직 구현 및 전체 상태 관리
  client/package.json
  client/src/Layout/Header.tsx
  client/src/Layout/Nav.tsx
  client/src/Layout/Store.tsx
  client/src/Layout/index.tsx
  client/src/app/login/Login.tsx
  client/src/app/login/page.tsx
  client/src/app/signup/Signup.tsx
  client/src/app/signup/page.tsx
  client/src/components/Header/HeaderArr.tsx
  client/src/components/Header/HeaderLogo.tsx
  client/src/components/Header/Headertype.tsx
  client/src/components/Header/InputModal.tsx
  client/src/components/Header/ListComp.tsx
  client/src/components/Header/LoginSide.tsx
  client/src/components/Header/NickModal.tsx
  client/src/components/Header/SearchDiv.tsx
  client/src/components/Header/SearchSide.tsx
  client/src/components/Header/useOutsideClick.tsx
  client/src/components/HeaderIcon.tsx
  client/src/components/Login/Button/LoginBtn.tsx
  client/src/components/Login/Button/SmallBtn.tsx
  client/src/components/Login/Container/LoginWindow.tsx
  client/src/components/Login/Container/OAuthCon.tsx
  client/src/components/Login/LoginInput.tsx
  client/src/components/Login/LoginModal.tsx
  client/src/components/Login/contextAPI/ModalProvider.tsx
  client/src/components/Login/contextAPI/useModal.tsx
  client/src/components/Navbar/NavRoute.tsx
  client/src/components/Navbar/Rank/RankClose.tsx
  client/src/components/Navbar/Rank/RankMenu.tsx
  client/src/components/Navbar/Rank/RankModal.tsx
  client/src/components/Navbar/currentRank.tsx
  client/src/components/login.tsx
  client/src/components/signup/ProfileInput.tsx
  client/src/components/signup/SignupBind.tsx
  client/src/components/signup/SignupForm2.tsx
  client/src/components/signup/SignupInput.tsx
  client/src/hooks/useInput.tsx
  client/src/hooks/useInputValid.tsx
  client/src/hooks/useSignupSubmit.tsx
  client/tailwind.config.js
Labels: ✨ enhancement, 💻 frontend

#71 Be feat/like
  server/src/main/java/com/CreatorConnect/server/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/freeboard/entity/FreeBoard.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/like/entity/Like.java
  server/src/main/java/com/CreatorConnect/server/member/like/repository/LikeRepository.java
Labels: ✨ enhancement, 💾 backend

#73 Be feat/bookmark
  server/src/main/java/com/CreatorConnect/server/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
  server/src/main/java/com/CreatorConnect/server/member/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
Labels: ✨ enhancement, 💾 backend

#74 [be] feat: 피드백 게시판 태그 기능 추가
  server/src/main/java/com/CreatorConnect/server/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/dto/FeedbackBoardDto.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/dto/FeedbackBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/entity/FeedbackBoard.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/mapper/FeedbackBoardMapper.java
  server/src/main/java/com/CreatorConnect/server/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/freeboard/conroller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/tag/entity/TagToFeedbackBoard.java
  server/src/main/java/com/CreatorConnect/server/tag/repository/TagToFeedbackBoardRepository.java
  server/src/main/java/com/CreatorConnect/server/tag/repository/TagToFreeBoardRepository.java
  server/src/main/java/com/CreatorConnect/server/tag/service/FeedbackBoardTagService.java
  server/src/main/java/com/CreatorConnect/server/tag/service/FreeBoardTagService.java
Labels: ✨ enhancement, 💾 backend

#79 Be feat/member
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtAuthenticationToken.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/controller/FeedbackCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/controller/FreeCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/entity/FeedbackComment.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/entity/FreeComment.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/service/CommentService.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/service/FeedbackCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/comments/comment/service/FreeCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/dto/FeedbackBoardDto.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/entity/FeedbackBoard.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/entity/FreeBoard.java
  server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 🙇 invalid, 💾 backend

#82 be-feat/ member memberpage 수정
  server/src/main/java/com/CreatorConnect/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/dto/FeedbackBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/conroller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/dto/FreeBoardDto.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/entity/FreeBoard.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberFollowResponseDto.java
  server/src/main/java/com/CreatorConnect/server/response/ErrorResponder.java
  server/src/main/java/com/CreatorConnect/server/response/ErrorResponse.java
  server/src/main/java/com/CreatorConnect/server/response/MultiResponseDto.java
  server/src/main/java/com/CreatorConnect/server/response/PageInfo.java
  server/src/main/java/com/CreatorConnect/server/response/SingleResponseDto.java
Labels: 💾 backend

#83 Be feat/member
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/mapper/MemberMapper.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend

#92 Be feat/ bookmark, like
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/entity/FeedbackBoard.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/conroller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/entity/FreeBoard.java
  server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/like/entity/Like.java
Labels: 💾 backend

#93 [be] refactor: bookmark, like cascade 수정
  server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
  server/src/main/java/com/CreatorConnect/server/member/like/entity/Like.java
Labels: 💾 backend

#97 [be] fix: 댓글 대댓글 멤버검증 로직 추가 및 수정
  server/src/main/java/com/CreatorConnect/server/board/comments/feedbackcomment/service/FeedbackCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/comments/freecomment/service/FreeCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/common/service/ReCommentService.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/feedbackrecomment/controller/FeedbackReCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/feedbackrecomment/service/FeedbackReCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/freerecomment/controller/FreeReCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/freerecomment/service/FreeReCommentServiceImpl.java
Labels: 🔧 fix, 💾 backend

#100 Be feat/search
  server/src/main/java/com/CreatorConnect/server/board/search/controller/SearchController.java
  server/src/main/java/com/CreatorConnect/server/board/search/dto/SearchBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/search/dto/SearchMemberResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/search/dto/SearchResponseDTO.java
  server/src/main/java/com/CreatorConnect/server/board/search/dto/SearchResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/search/service/SearchService.java
  server/src/main/java/com/CreatorConnect/server/member/repository/MemberRepository.java
Labels: 💾 backend

#101 [be] refactor: 회원 수정 리팩토링
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend

#103 [be] refactor: 사이트 내 인기검색어 순위 구현
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/board/search/controller/SearchController.java
  server/src/main/java/com/CreatorConnect/server/board/search/entity/PopularSearch.java
  server/src/main/java/com/CreatorConnect/server/board/search/repository/PopularSearchRepository.java
  server/src/main/java/com/CreatorConnect/server/board/search/service/SearchService.java
Labels: 💾 backend

#104 [be] refactor: FeedbackBoard 연관관계 매핑 수정
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/entity/FeedbackBoard.java
Labels: 💾 backend

#106 [be] refactor: 유저 수정 페이지 리팩토링
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberDto.java
Labels: 💾 backend

#107 [be] feat: jobboard bookmark, like 기능 구현
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/controller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/controller/JobBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/entity/JobBoard.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/service/JobBoardService.java
  server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/like/entity/Like.java
Labels: 💾 backend

#108 [be] feat: 유저 페이지에 jobboard bookmark, like 추가
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
Labels: 💾 backend

#111 [be] fix: 게시물 좋아요, 북마크 동작 수정
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/service/JobBoardService.java
Labels: 🤪 bug, 🔧 fix, 💾 backend

#109 Fe feat/profile
  client/package.json
  client/src/apis/auth.ts
  client/src/apis/board/bookmarked.ts
  client/src/apis/board/index.ts
  client/src/apis/board/liked.ts
  client/src/apis/board/written.ts
  client/src/apis/follow.ts
  client/src/apis/followers.ts
  client/src/apis/followings.ts
  client/src/apis/index.ts
  client/src/apis/member.ts
  client/src/apis/password.ts
  client/src/app/profile/FollowerModal.tsx
  client/src/app/profile/FollowingModal.tsx
  client/src/app/profile/ProfileBoard.tsx
  client/src/app/profile/ProfileBookmarkedBoardList.tsx
  client/src/app/profile/ProfileCard.tsx
  client/src/app/profile/ProfileLikedBoardList.tsx
  client/src/app/profile/ProfileWrittenBoardList.tsx
  client/src/app/profile/[memberId]/ProfileNav.tsx
  client/src/app/profile/[memberId]/edit/ProfileEditForm.tsx
  client/src/app/profile/[memberId]/edit/page.tsx
  client/src/app/profile/[memberId]/page.tsx
  client/src/components/Board/BoardFooter.tsx
  client/src/components/Board/BoardHeader.tsx
  client/src/components/Board/Form/Input.tsx
  client/src/components/Board/Form/Photo.tsx
  client/src/components/InfiniteScrollContainer.tsx
  client/src/components/Skeleton/ProfileBoard.tsx
  client/src/components/Skeleton/ProfileCard.tsx
  client/src/components/Skeleton/index.tsx
  client/src/components/Svg/NotSearch.tsx
  client/src/css/globals.css
  client/src/hooks/query/index.ts
  client/src/hooks/query/useFetchBookmarkedBoardList.ts
  client/src/hooks/query/useFetchComments.ts
  client/src/hooks/query/useFetchFollowers.ts
  client/src/hooks/query/useFetchFollowings.ts
  client/src/hooks/query/useFetchLikedBoardList.ts
  client/src/hooks/query/useFetchMemeber.ts
  client/src/hooks/query/useFetchWrittenBoardList.ts
  client/src/store/useMemberStore.ts
  client/src/types/api/auth.ts
  client/src/types/api/board/bookmarked.ts
  client/src/types/api/board/index.ts
  client/src/types/api/board/liked.ts
  client/src/types/api/board/written.ts
  client/src/types/api/follow.ts
  client/src/types/api/followers.ts
  client/src/types/api/followings.ts
  client/src/types/api/index.ts
  client/src/types/api/member.ts
  client/src/types/api/password.ts
  client/tailwind.config.js
Labels: 💻 frontend

#117 Be code refactoring
  server/src/main/java/com/CreatorConnect/server/board/comments/feedbackcomment/controller/FeedbackCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/comments/freecomment/controller/FreeCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/controller/JobCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/comments/jobcomment/service/JobCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/controller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/controller/JobBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/service/JobBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/notice/controller/NoticeController.java
  server/src/main/java/com/CreatorConnect/server/board/notice/service/NoticeService.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/feedbackrecomment/controller/FeedbackReCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/freerecomment/controller/FreeReCommentController.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/jobrecomment/controller/JobReCommentController.java
  server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend

#118 Be code refactoring
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
Labels: 💾 backend

#119 [be] refactor: code refactoring
  server/src/main/java/com/CreatorConnect/server/board/categories/category/controller/CategoryController.java
  server/src/main/java/com/CreatorConnect/server/board/categories/feedbackcategory/controller/FeedbackCategoryController.java
  server/src/main/java/com/CreatorConnect/server/board/categories/jobcategory/controller/JobCategoryController.java
Labels: 💾 backend

#120 Be oauth2 login refactoring
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/utils/CustomAuthorityUtils.java
Labels: 💾 backend

#121 [be] refactor: oauth2 login refactoring
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend

#122 [be] refactor: oauth2 login refactoring
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
Labels: 💾 backend

#125 [be] refactor: 게시글 목록 조회시 bookmarked, liked 조회 수정
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/service/JobBoardService.java
Labels: 💾 backend

#126 Be refactoring
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
Labels: 💾 backend

#127 [be] refactor: oauth2 redirect path 수정
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
Labels: 💾 backend

#128 [oauth2 redirect path 수정]
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
Labels: 💾 backend

#129 [be] refactor: 회원가입 오류 메세지 수정
  server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/repository/MemberRepository.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend

#130 Fe feat/design
  client/next.config.js
  client/src/Layout/Header.tsx
  client/src/Layout/Nav.tsx
  client/src/Layout/index.tsx
  client/src/apis/auth.ts
  client/src/app/feedback/edit/Form.tsx
  client/src/app/feedback/write/Form.tsx
  client/src/app/login/Login.tsx
  client/src/app/login/oauth/page.tsx
  client/src/app/login/page.tsx
  client/src/app/profile/[memberId]/edit/ProfileEditForm.tsx
  client/src/app/promotion/edit/Form.tsx
  client/src/app/promotion/write/Form.tsx
  client/src/app/signup/Signup.tsx
  client/src/app/signup/page.tsx
  client/src/components/AuthForm/Input.tsx
  client/src/components/Header/HeaderLogo.tsx
  client/src/components/Header/SearchSide.tsx
  client/src/components/InfoDropdown.tsx
  client/src/components/Login/MyLogInModal.tsx
  client/src/components/Navbar/NavRoute.tsx
  client/src/components/Navbar/Rank/RankMenu.tsx
  client/src/components/Ticker.tsx
  client/src/components/signup/MySignUpModal.tsx
  client/src/css/globals.css
  client/src/libs/validate.ts
  client/src/store/useLogInStore.ts
  client/src/store/useMemberStore.ts
  client/src/store/useSignUpStore.ts
  client/src/types/api/auth.ts
  client/src/types/api/member.ts
  client/tailwind.config.js
Labels: 💻 frontend

#140 [be] feat: 인기 급상승 영상 목록 조회 기능 추가
  server/build.gradle
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/exception/ExceptionCode.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/controller/YoutubeApiController.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/dto/YoutubeApiDto.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/entity/VideoEntity.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/entity/VideoPK.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/mapper/YoutubeApiMapper.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/repository/YoutubeApiRepository.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
Labels: ✨ enhancement, 💾 backend

#141 [be] fix: 유튜브 api
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/controller/YoutubeApiController.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
Labels: 🔧 fix, 💾 backend

#142 Fe feat/design
  client/package.json
  client/src/app/feedback/[boardId]/Board/index.tsx
  client/src/app/feedback/[boardId]/page.tsx
  client/src/app/free/[boardId]/Board/index.tsx
  client/src/app/free/[boardId]/page.tsx
  client/src/app/job/[boardId]/Board/index.tsx
  client/src/app/job/[boardId]/page.tsx
  client/src/app/profile/FollowerModal.tsx
  client/src/app/profile/FollowingModal.tsx
  client/src/app/profile/ProfileBoard.tsx
  client/src/app/profile/ProfileCard.tsx
  client/src/app/profile/ProfileWrittenBoardList.tsx
  client/src/app/profile/[memberId]/ProfileNav.tsx
  client/src/app/profile/[memberId]/edit/ProfileEditForm.tsx
  client/src/app/profile/[memberId]/page.tsx
  client/src/app/promotion/[boardId]/Board/index.tsx
  client/src/app/promotion/[boardId]/page.tsx
  client/src/components/Avatar.tsx
  client/src/components/Board/BoardASide.tsx
  client/src/components/Board/BoardComment.tsx
  client/src/components/Board/BoardCommentForm.tsx
  client/src/components/Board/BoardComments.tsx
  client/src/components/Board/BoardFooter.tsx
  client/src/components/Board/BoardHeader.tsx
  client/src/components/Board/BoardRecomment.tsx
  client/src/components/Board/BoardRecommentForm.tsx
  client/src/components/Board/Form/Photo.tsx
  client/src/components/Board/Navigation.tsx
  client/src/components/BoardMain/ContentFooter.tsx
  client/src/components/Pagination.tsx
  client/src/components/Svg/NotSearch.tsx
  client/src/css/globals.css
  client/src/libs/time.ts
  client/src/types/api/member.ts
Labels: 💻 frontend

#143 be 회원가입시 이메일 인증 로직 추가
  server/build.gradle
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/HttpServletWrappingFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/OauthController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/OAuth2MemberService.java
  server/src/main/java/com/CreatorConnect/server/helper/email/EmailConfiguration.java
  server/src/main/java/com/CreatorConnect/server/helper/email/EmailSendable.java
  server/src/main/java/com/CreatorConnect/server/helper/email/EmailSender.java
  server/src/main/java/com/CreatorConnect/server/helper/email/MockEmailSendable.java
  server/src/main/java/com/CreatorConnect/server/helper/email/MockExceptionEmailSendable.java
  server/src/main/java/com/CreatorConnect/server/helper/email/SimpleEmailSendable.java
  server/src/main/java/com/CreatorConnect/server/helper/email/TemplateEmailSendable.java
  server/src/main/java/com/CreatorConnect/server/helper/event/MemberRegistrationApplicationEvent.java
  server/src/main/java/com/CreatorConnect/server/helper/event/MemberRegistrationEventListener.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberDto.java
  server/src/main/java/com/CreatorConnect/server/member/dto/MemberResponseDto.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
  server/src/main/resources/templates/email-registration-member.html
Labels: 💾 backend

#144 Fe feat/board UI
  client/src/app/HomeMain.tsx
  client/src/app/feedback/FeedbackContentItem.tsx
  client/src/app/feedback/FeedbackMain.tsx
  client/src/app/free/ContentItem.tsx
  client/src/app/free/FreeMain.tsx
  client/src/app/job/JobContentItem.tsx
  client/src/app/job/JobMain.tsx
  client/src/app/notice/NoticeContetnItem.tsx
  client/src/app/notice/NoticeMain.tsx
  client/src/app/promotion/PromotionContentItem.tsx
  client/src/app/promotion/PromotionMain.tsx
  client/src/components/BoardMain/ContentFooter.tsx
  client/src/components/BoardMain/Slide/BannerSlide.tsx
  client/src/components/BoardMain/Slide/FeedbackPostsSlide.tsx
  client/src/components/BoardMain/Slide/FreePostsSlide.tsx
  client/src/components/Svg/NoDataExists.tsx
  client/src/css/globals.css
Labels: 💻 frontend

#145 OAuth 로그인 구현 및 인기검색어 코드 충돌 수정
  client/src/app/login/Login.tsx
  client/src/app/login/oauth/OAuthLogin.tsx
  client/src/app/login/oauth/page.tsx
  client/src/components/Header/InputModal.tsx
  client/src/components/Header/LoginSide.tsx
  client/src/components/Login/Button/LoginBtn.tsx
  client/src/components/Login/OAuthContainer.tsx
  client/src/components/Navbar/Rank/RankClose.tsx
  client/src/components/Navbar/Rank/RankModal.tsx
  client/src/components/Navbar/currentRank.tsx
  client/src/components/signup/SignupBind.tsx
  client/src/store/useMemberStore.ts
Labels: 💻 frontend

#147 [be] Refeactory : 멤버 인증 로직 변경 - 쿼리 최적화
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend, 🔨Refactor

#148 [be] fix : youtubeId 추가
  server/src/main/java/com/CreatorConnect/server/youtubeapi/dto/YoutubeApiDto.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/entity/VideoEntity.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/mapper/YoutubeApiMapper.java
  server/src/main/java/com/CreatorConnect/server/youtubeapi/service/YoutubeApiService.java
Labels: 🔧 fix, 💾 backend

#152 Be refactor/member
  server/src/main/java/com/CreatorConnect/server/board/search/controller/SearchController.java
Labels: 💾 backend

#158 [be] feat: Add FeedbackBoard and implement Dto
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/repository/PromotionBoardRepository.java
Labels: 💾 backend

#159 Be refactor/member
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
Labels: 💾 backend

#161 [be] refactor: oauth2 배포
  server/src/main/java/com/CreatorConnect/server/auth/oauth/config/OAuth2Configuration.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/KakaoApiService.java
Labels: 💾 backend

#162 Fe feat/search
  client/package.json
  client/src/apis/index.ts
  client/src/apis/keywords.ts
  client/src/apis/search.ts
  client/src/app/feedback/edit/Form.tsx
  client/src/app/feedback/edit/page.tsx
  client/src/app/feedback/write/Form.tsx
  client/src/app/feedback/write/page.tsx
  client/src/app/free/edit/Form.tsx
  client/src/app/free/edit/page.tsx
  client/src/app/free/write/Form.tsx
  client/src/app/free/write/page.tsx
  client/src/app/job/edit/Form.tsx
  client/src/app/job/edit/page.tsx
  client/src/app/job/write/Form.tsx
  client/src/app/job/write/page.tsx
  client/src/app/promotion/edit/Form.tsx
  client/src/app/promotion/edit/page.tsx
  client/src/app/promotion/write/Form.tsx
  client/src/app/promotion/write/page.tsx
  client/src/app/search/SearchLists.tsx
  client/src/app/search/page.tsx
  client/src/components/Board/BoardComment.tsx
  client/src/components/Board/BoardFooter.tsx
  client/src/components/Board/BoardHeader.tsx
  client/src/components/Board/BoardRecommentForm.tsx
  client/src/components/Board/Form/JobCategory.tsx
  client/src/components/Header/InputModal.tsx
  client/src/components/Header/SearchDiv.tsx
  client/src/components/KeywordCloud.tsx
  client/src/css/globals.css
  client/src/hooks/query/index.ts
  client/src/hooks/query/useFetchKeywords.ts
  client/src/hooks/query/useFetchSearch.ts
  client/src/libs/time.ts
  client/src/types/api/index.ts
  client/src/types/api/keywords.ts
  client/src/types/api/search.ts
  client/tailwind.config.js
Labels: 💻 frontend

#164 [be] feat: Add FeedbackBoard implement Entity
  server/src/main/java/com/CreatorConnect/server/board/categories/category/entity/Category.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
Labels: 💾 backend

#166 [be] fix : 피드백 카테고리별 카테고리 전체 검색 추가
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/repository/FeedbackBoardRepository.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
Labels: 🔧 fix, 💾 backend

#167 [be] feat: Add FeedbackBoard implement Mapper
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/mapper/PromotionBoardMapper.java
Labels: 💾 backend

#168 [fe] fix: 코드 정리 및 요구사항 반영
  client/src/app/feedback/edit/Form.tsx
  client/src/app/feedback/write/Form.tsx
  client/src/app/free/edit/Form.tsx
  client/src/app/free/write/Form.tsx
  client/src/app/job/edit/Form.tsx
  client/src/app/job/write/Form.tsx
  client/src/app/promotion/edit/Form.tsx
  client/src/app/promotion/write/Form.tsx
  client/src/components/Header/InputModal.tsx
  client/src/components/Header/SearchDiv.tsx
  client/src/components/KeywordCloud.tsx
  client/src/hooks/query/useFetchKeywords.ts
  client/src/hooks/useTags.ts
  client/src/types/api/keywords.ts
Labels: 💻 frontend

#169 [be] feat: Add FeedbackBoard implement service
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
Labels: 💾 backend

#177 [fe] fix: 로그아웃 시 멤버 삭제
  client/src/app/login/Login.tsx
  client/src/components/Header/HeaderArr.tsx
  client/src/components/Header/HeaderLogo.tsx
  client/src/components/Header/NickModal.tsx
  client/src/components/Login/linkList.ts
  client/src/components/Navbar/NavRoute.tsx
  client/src/public/logo/main-logo4.png
Labels: 💻 frontend

#181 Be feat/promotionboard
  server/src/main/java/com/CreatorConnect/server/board/categories/category/entity/Category.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/mapper/PromotionBoardMapper.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/repository/PromotionBoardRepository.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/search/service/SearchService.java
  server/src/main/java/com/CreatorConnect/server/board/tag/entity/Tag.java
  server/src/main/java/com/CreatorConnect/server/member/bookmark/entity/Bookmark.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/like/entity/Like.java
Labels: 💾 backend

#183 Next hydration-error 해결 / Footer 제작
  client/src/Layout/Footer.tsx
  client/src/app/FeedbackPostsSlide.tsx
  client/src/app/FreePostsSlide.tsx
  client/src/app/feedback/FeedbackCategories.tsx
  client/src/app/feedback/FeedbackContentItem.tsx
  client/src/app/feedback/FeedbackMain.tsx
  client/src/app/free/ContentItem.tsx
  client/src/app/free/FreeMain.tsx
  client/src/app/free/popularposts.tsx
  client/src/app/job/JobCategories.tsx
  client/src/app/job/JobContentItem.tsx
  client/src/app/job/JobMain.tsx
  client/src/app/promotion/PromotionMain.tsx
  client/src/components/Board/BoardThumbnail.tsx
  client/src/components/BoardMain/ContentFooter.tsx
  client/src/components/BoardMain/SideCategories.tsx
  client/src/components/BoardMain/SortPosts.tsx
  client/src/components/BoardMain/TagItem.tsx
  client/src/components/Footer/FooterContent.tsx
  client/src/components/RightSideButton.tsx
  client/src/libs/index.ts
Labels: 💻 frontend

#184 Be refactor/member
  server/build.gradle
  server/src/main/java/com/CreatorConnect/server/ServerApplication.java
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/config/WebConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/TokenService.java
  server/src/main/java/com/CreatorConnect/server/auth/redis/RedisConfig.java
  server/src/main/java/com/CreatorConnect/server/auth/redis/refreshtoken/RefreshToken.java
  server/src/main/java/com/CreatorConnect/server/auth/redis/refreshtoken/RefreshTokenController.java
  server/src/main/java/com/CreatorConnect/server/auth/redis/refreshtoken/RefreshTokenRepository.java
  server/src/main/java/com/CreatorConnect/server/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/CreatorConnect/server/board/search/entity/PopularSearch.java
  server/src/main/java/com/CreatorConnect/server/board/search/service/SearchService.java
Labels: 💾 backend

#185 [be] fix: fix promotion service
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
Labels: 💾 backend

#186 [be] fix: fix promotion controller
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
Labels: 💾 backend

#190 [fe] fix: 검색창와 검색어, 워드 클라우드 레이아웃 조정 및 페비콘 / error / 404 페이지 추가
  client/public/favicon/android-icon-144x144.png
  client/public/favicon/android-icon-192x192.png
  client/public/favicon/android-icon-36x36.png
  client/public/favicon/android-icon-48x48.png
  client/public/favicon/android-icon-72x72.png
  client/public/favicon/android-icon-96x96.png
  client/public/favicon/apple-icon-114x114.png
  client/public/favicon/apple-icon-120x120.png
  client/public/favicon/apple-icon-144x144.png
  client/public/favicon/apple-icon-152x152.png
  client/public/favicon/apple-icon-180x180.png
  client/public/favicon/apple-icon-57x57.png
  client/public/favicon/apple-icon-60x60.png
  client/public/favicon/apple-icon-72x72.png
  client/public/favicon/apple-icon-76x76.png
  client/public/favicon/apple-icon-precomposed.png
  client/public/favicon/apple-icon.png
  client/public/favicon/favicon-16x16.png
  client/public/favicon/favicon-32x32.png
  client/public/favicon/favicon-96x96.png
  client/public/favicon/favicon.ico
  client/public/favicon/manifest.json
  client/public/favicon/ms-icon-144x144.png
  client/public/favicon/ms-icon-150x150.png
  client/public/favicon/ms-icon-310x310.png
  client/public/favicon/ms-icon-70x70.png
  client/src/app/error.tsx
  client/src/app/layout.tsx
  client/src/app/not-found.tsx
  client/src/app/search/SearchLists.tsx
  client/src/app/search/page.tsx
  client/src/components/Header/InputModal.tsx
  client/src/components/Header/SearchDiv.tsx
  client/src/css/globals.css
  client/tailwind.config.js
Labels: 💻 frontend

#191 [be] fix: fix promotion member
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/entity/Member.java
Labels: 💾 backend

#192 [fe] feature: 로고, 로그인 css, 리프레시 토큰
  client/src/Layout/Header.tsx
  client/src/app/login/Login.tsx
  client/src/components/Header/AuthCheck.tsx
  client/src/components/Header/HeaderLogo.tsx
  client/src/components/Login/Button/SignupRouteBtn.tsx
  client/src/components/Login/OAuthContainer.tsx
  client/src/public/images/naver.svg
Labels: 💻 frontend

#196 [be] refactor: search refactor
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
  server/src/main/java/com/CreatorConnect/server/board/search/controller/SearchController.java
  server/src/main/java/com/CreatorConnect/server/board/search/entity/PopularSearch.java
  server/src/main/java/com/CreatorConnect/server/board/search/service/SearchService.java
Labels: 💾 backend

#199 [be] refactor: search response
  server/src/main/java/com/CreatorConnect/server/board/search/dto/SearchBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/search/service/SearchService.java
Labels: 💾 backend

#204 Be refactor/member
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/dto/PromotionBoardResponseDto.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/entity/PromotionBoard.java
Labels: 💾 backend

#205 [be] refactor: feedbackcomment
  server/src/main/java/com/CreatorConnect/server/board/comments/feedbackcomment/service/FeedbackCommentServiceImpl.java
  server/src/main/java/com/CreatorConnect/server/board/recomments/feedbackrecomment/service/FeedbackReCommentServiceImpl.java
Labels: 💾 backend

#206 [be] refactor: promotionboard
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
Labels: 💾 backend

#216 [fe] feat: 일부 페이지 SSR 적용
  client/public/logo/logo.png
  client/src/apis/ssr.ts
  client/src/app/feedback/[boardId]/Board/index.tsx
  client/src/app/feedback/[boardId]/page.tsx
  client/src/app/free/[boardId]/Board/index.tsx
  client/src/app/free/[boardId]/page.tsx
  client/src/app/job/[boardId]/Board/index.tsx
  client/src/app/job/[boardId]/page.tsx
  client/src/app/loading.tsx
  client/src/app/not-found.tsx
  client/src/app/profile/ProfileCard.tsx
  client/src/app/profile/[memberId]/page.tsx
  client/src/app/promotion/[boardId]/Board/index.tsx
  client/src/app/promotion/[boardId]/page.tsx
  client/src/app/search/page.tsx
  client/src/hooks/query/useFetchFeedbackBoard.ts
  client/src/hooks/query/useFetchFreeBoard.ts
  client/src/hooks/query/useFetchJobBoard.ts
  client/src/hooks/query/useFetchMemeber.ts
  client/src/hooks/query/useFetchPromotionBoard.ts
  client/src/libs/index.ts
  client/src/libs/metadata.ts
Labels: 💻 frontend

#224 Be refactor/folder refactoring
  server/src/main/java/com/CreatorConnect/server/auth/jwt/TokenService.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshToken.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenController.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenRepository.java
  server/src/main/java/com/CreatorConnect/server/redis/RedisConfig.java
Labels: 💾 backend

#228 [be] refactor: promotionboard
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
Labels: 💾 backend

#229 [be] refactor: search
  server/src/main/java/com/CreatorConnect/server/board/search/entity/PopularSearch.java
Labels: 💾 backend

#234 [be] fix: build.gradle Task 수정
  server/build.gradle
Labels: 💾 backend

#237 [be] fix: RedisService 수정
  server/src/main/java/com/CreatorConnect/server/redis/RedisConfig.java
  server/src/main/java/com/CreatorConnect/server/redis/RedisService.java
Labels: 💾 backend

#239 [fe]: fix: 검색 안 되는 문제 해결
  client/src/app/profile/ProfileCard.tsx
  client/src/app/search/SearchLists.tsx
  client/src/app/search/page.tsx
Labels: 💻 frontend

#218 [fe] fix : 헤더 로그인 상태 유지, AuthCheck 주석
  client/src/Layout/Header.tsx
  client/src/components/Header/AuthCheck.tsx
  client/src/components/Header/LoginSide.tsx
  client/src/components/Header/NickModal.tsx
  client/src/components/signup/SignupBind.tsx
  client/src/store/useMemberStore.ts
Labels: 💻 frontend

#241 Be refactor/logout redirect 수정
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/TokenService.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenRepository.java
Labels: 💾 backend

#242 [be] refactor: logout 수정
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtLogoutFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenController.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
Labels: 💾 backend

#243 [fe-fix] 로그아웃 재 구현
  client/src/components/Header/NickModal.tsx
Labels: 💻 frontend

#244 Be refactor/test
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/HttpServletWrappingFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenController.java
Labels: 💾 backend

#245 [FE-Fix] refresh 토큰 키값 수정
  client/src/app/login/Login.tsx
Labels: 💻 frontend

#246 Be refactor/logout
  server/src/main/java/com/CreatorConnect/server/auth/config/SecurityConfiguration.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenController.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
Labels: 💾 backend

#247 Be refactor/ mypage, followed
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
  server/src/main/java/com/CreatorConnect/server/redis/RedisConfig.java
  server/src/main/java/com/CreatorConnect/server/redis/RedisService.java
Labels: 💾 backend

#251 Be feat/promotionboard
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
Labels: 💾 backend

#252 Be refactor/ member 인증 방식 변경
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/controller/FeedbackBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/feedbackboard/service/FeedbackBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/controller/FreeBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/controller/JobBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/jobboard/service/JobBoardService.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/controller/PromotionBoardController.java
  server/src/main/java/com/CreatorConnect/server/board/promotionboard/service/PromotionBoardService.java
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
  server/src/main/java/com/CreatorConnect/server/member/service/MemberService.java
Labels: 💾 backend

#253 [be] feat: ExpiredJwtException 처리 로직
  server/src/main/java/com/CreatorConnect/server/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/CreatorConnect/server/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/CreatorConnect/server/auth/jwt/refreshtoken/RefreshTokenController.java
  server/src/main/java/com/CreatorConnect/server/exception/JwtVerificationException.java
Labels: 💾 backend

#254 [be] feat: member page
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
Labels: 💾 backend

#255 [be] feat: member page
  server/src/main/java/com/CreatorConnect/server/member/controller/MemberController.java
Labels: 💾 backend

#256 [be] refactor: oauth login member token refactoring
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/KakaoController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/controller/NaverController.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/CreatorConnect/server/auth/oauth/service/OAuth2MemberService.java
Labels: 💾 backend

#258 [be] refactor: freeboard tag
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
Labels: 💾 backend

#259 [be] refactor: freeboard tag
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
Labels: 💾 backend

#260 [be] refactor: freeboard tag
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
Labels: 💾 backend

#261 [be] refactor: freeboard tag
  server/src/main/java/com/CreatorConnect/server/board/freeboard/service/FreeBoardService.java
Labels: 💾 backend

#263 실검, 로고 사이즈, AuthCheck 등
  client/src/Layout/Header.tsx
  client/src/components/Header/AuthCheck.tsx
  client/src/components/Header/HeaderLogo.tsx
  client/src/components/Header/LoginSide.tsx
  client/src/components/Navbar/Rank/RankClose.tsx
  client/src/components/Navbar/Rank/RankModal.tsx
  client/src/hooks/useCurrentRank.tsx
  client/tailwind.config.js
Labels: 💻 frontend
